### PR TITLE
Output proper address when listing only one service.

### PR DESCRIPTION
**Pull request by miracle2k**

### CODE REVIEW

**Comment by titanous** [comment]
LGTM. Would you accept the DCO for this commit?

**Comment by miracle2k** [comment]
Can you be convinced of not requiring the github name in the sign off message? At least then the -s flag wouldn't require manual intervention.

**Comment by titanous** [comment]
Hmm, didn't know about the `-s` flag. Good call, we'll drop it. Update the message again?

**Comment by titanous** [comment]
Done in flynn/flynn-guide@4c0cb853d5dc84a6e5ef5b64474b4cd08a64f6a9. Thanks for pointing this out!

**Comment by titanous** [comment]
Thanks!

**Pull request merged**
